// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF40fK8ohR_2faCzU45oQJT1Rizwvu_oc',
    appId: '1:1071534318503:web:27fbee5af91d0161510c82',
    messagingSenderId: '1071534318503',
    projectId: 'e-commerce-app-10541',
    authDomain: 'e-commerce-app-10541.firebaseapp.com',
    storageBucket: 'e-commerce-app-10541.firebasestorage.app',
    measurementId: 'G-EKD1M447TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClsJNsmHdBH2lkrry7pzDSHRMP3IPQsd0',
    appId: '1:1071534318503:android:35b050a13796d6d9510c82',
    messagingSenderId: '1071534318503',
    projectId: 'e-commerce-app-10541',
    storageBucket: 'e-commerce-app-10541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8upMu-D4hSKu49gwTjEqwpioYFSuSGNI',
    appId: '1:1071534318503:ios:d9dcd327fb470794510c82',
    messagingSenderId: '1071534318503',
    projectId: 'e-commerce-app-10541',
    storageBucket: 'e-commerce-app-10541.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8upMu-D4hSKu49gwTjEqwpioYFSuSGNI',
    appId: '1:1071534318503:ios:d9dcd327fb470794510c82',
    messagingSenderId: '1071534318503',
    projectId: 'e-commerce-app-10541',
    storageBucket: 'e-commerce-app-10541.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF40fK8ohR_2faCzU45oQJT1Rizwvu_oc',
    appId: '1:1071534318503:web:088e33badc5d5c5f510c82',
    messagingSenderId: '1071534318503',
    projectId: 'e-commerce-app-10541',
    authDomain: 'e-commerce-app-10541.firebaseapp.com',
    storageBucket: 'e-commerce-app-10541.firebasestorage.app',
    measurementId: 'G-T7Y2YEDFXM',
  );
}
